"""
generated by
http://valchemist-inn.rhcloud.com/
"""
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, Date, String, Table, Text, Float, ForeignKey
from sqlalchemy.orm import sessionmaker, relationship, backref

Base = declarative_base()


class track(Base):
    __tablename__ = "tracks"
    id = Column(Text, primary_key=True, unique=True)
    name = Column(Text)

    def __init__(self, track):
        self.track = track


class location(Base):
    __tablename__ = "locations"
    id = Column(Integer, primary_key=True, unique=True)
    name = Column(Text)
    capacity = Column(Integer)
    notes = Column(Text)
    av = Column(Integer)
    av_notes = Column(Text)


class speaker(Base):
    __tablename__ = "speakers"
    id = Column(Integer, primary_key=True, unique=True)
    name = Column(Text)
    phone_number = Column(Text)
    email_address = Column(Text)
    prefered_contact_method = Column(Text)
    notes = Column(Text)


class event(Base):
    __tablename__ = "events"
    location_id = Column(Integer, ForeignKey(location.id)) # one or more
    track_id = Column(Integer, ForeignKey(track.id)) # one or more
    speaker_id = Column(Integer, ForeignKey(speaker.id)) # one or more
    start = Column(Date) # later when checking for conflicts check in 10 minute intervals
    end = Column(Date)
    title = Column(Text)
    description = Column(Text)
    av_needs = Column(Text)
    private = Column(Integer, default=0)
    all_date = Column(Integer, default=0)
    duration = Column(Integer, default=50)
    event_id = Column(Integer, primary_key=True, unique=True)


class spreadsheetdb(Base):
    __tablename__ = "spreadsheetdb"
    id = Column(Integer, primary_key=True, unique=True)
    start_date = Column(String)
    start_time = Column(String)
    end_date = Column(String)
    end_time = Column(String)
    location = Column(String)
    track = Column(String)
    title = Column(String)
    presenters = Column(String)
    book_description = Column(String)
    duration = Column(String)
    av_needs = Column(String)
    all_day_event = Column(String)
    private = Column(String)




    """ 
'End Date': '4/26/2015'
'All Day Event': 'TRUE'
'Title': 'Chaos Machine'
'Track': 'Mayhem'
'Private': 'PUBLIC'
'Start Time': '16:00'
'Book Description': 'The Chaos machine returns to shape your wildest engineering imagination into a functioning beacon of collective brilliance. Find some old friends or new acquaintances to help build the machine from the ground up!'
'Presenters': ''
'End Time': '16:00'
'Location': 'Lobby'
'Duration': ''
'Start Date': '4/24/2015'
'AV Needs': ''

    """

#    def __repr__(self):
#        return "event()"

#association tables
    #event_speakers = 

if __name__ == '__main__':
    print('running sqlalchemy ' + sqlalchemy.__version__)
    engine = create_engine(r'sqlite:////home/jhice/projects/schedcsv/schedule.db', echo=True) #connect to database
    Base.metadata.create_all(engine) #Lets create the actual sqlite database and schema!
    print('database created: schedule.db')
