"""
generated by
http://valchemist-inn.rhcloud.com/
"""
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, Date, String, Text, Float, ForeignKey
from sqlalchemy.orm import sessionmaker, relationship, backref

Base = declarative_base()


class tracks(Base):
	__tablename__ = "tracks"
	id = Column(Text, primary_key=True, unique=True)
	name = Column(Text)


class locations(Base):
	__tablename__ = "locations"
	id = Column(Integer, primary_key=True, unique=True)
	name = Column(Text)
	capacity = Column(Integer)
	notes = Column(Text)
	av = Column(Integer)
	av_notes = Column(Text)


class speakers(Base):
	__tablename__ = "speakers"
	id = Column(Integer, primary_key=True, unique=True)
	name = Column(Text)
	phone_number = Column(Text)
	email_address = Column(Text)
	prefered_contact_method = Column(Text)
	notes = Column(Text)


class events(Base):
	__tablename__ = "events"
	location_id = Column(Integer, ForeignKey(locations.id))
	track_id = Column(Integer, ForeignKey(tracks.id))
	speaker_id = Column(Integer, ForeignKey(speakers.id))
	start = Column(Date)
	end = Column(Date)
	title = Column(Text)
	description = Column(Text)
	av_needs = Column(Text)
	private = Column(Integer, default=0)
	all_date = Column(Integer, default=0)
	duration = Column(Integer, default=50)
	event_id = Column(Integer, primary_key=True, unique=True)


if __name__ == '__main__':
	print('running sqlalchemy ' + sqlalchemy.__version__)
	engine = create_engine(r'sqlite:////home/jhice/projects/schedcsv/schedule.db', echo=True) #connect to database
	Base.metadata.create_all(engine) #Lets create the actual sqlite database and schema!
	print('database created: schedule.db')
